### ISSUE TITLE
Connecting to MongoDb in Docker throws uncaught promise (in wsl2)

### ISSUE THREAD

**Issue by RobertFent** [denodrivers/deno_mongo#200]
I'm trying to connect the MongoClient to a MongDb container running in Docker.<br>
The docker container is running in wsl2 with the wsl ip 172.18.96.38 and exposing port 27017.

Connecting to it with the following code leads to an error:
```ts
import { MongoClient } from "https://deno.land/x/mongo@v0.23.0/mod.ts";

const uri = 'mongodb://admin:admin@172.18.96.38:27017'
this.mClient = new MongoClient();
await this.mClient.connect(uri);
```
```
error: Uncaught (in promise) Error: MongoError: "Connection failed: MongoError: {\"ok\":0,\"errmsg\":\"no such command: 'hello'\",\"code\":59,\"codeName\":\"CommandNotFound\"}"
      throw new MongoError(`Connection failed: ${e.message || e}`);
            ^
    at MongoClient.connect (https://deno.land/x/mongo@v0.23.0/src/client.ts:26:13)
    at async Function.initMongoClient (file:///home/robert/repos/myDenoWebsite/backend/src/utils/mongoClientWrapper.ts:54:9)
```
According to the errmsg the error is 'no such command: 'hello'.
What does this mean?

This is my docker-compose.yml for mongo btw:
```yml
version: '3.8'

services:
  mongodb:
    image: mongo:4.4-bionic
    container_name: my-mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodb:
  mongoconfig:
```
